### ISSUE TITLE
Skip through and skip to are unstable

### ISSUE THREAD

**Issue by StevenCostiou** [pharo-spec/ScriptableDebugger#13]
Tests do not pass anymore and freeze or crash the image.
This is mostly due to a wrong usage of the skip api of Sindarin that is not complete enough (only considers messages and assignments).

**Comment by adri09070** [comment]
Now, with #20 (and #24) tests pass but these commands can still freeze the image if there is something that is neither a message nor an assignment between the starting point and the point of arrival. 

This can also freeze the image if the user wants to skip to a block and I don't know why. Maybe that the related methods don't find the correct node/pc as it is in a different context (a block itself being a different context).

I will make different issues for these.
