### ISSUE TITLE
When enabling #timesRepeat: to be optimised, fail: SindarinCommandsTest>>testStepToNextCallInClassNeverFinishes 

### ISSUE THREAD

**Issue by MarcusDenker** [pharo-spec/ScriptableDebugger#36]
I would like to enable #timesRepea: to compile as an optimized construct by default 

(see https://github.com/pharo-project/pharo/pull/11439)

But SindarinCommandsTest>>testStepToNextCallInClassNeverFinishes  relies on the method to be not optimised.

A minimal change would be to have it for now as

```
acceptVisitorNeverFinishes: aVisitor
	<compilerOptions: #(- optionInlineTimesRepeat)>
	10000 timesRepeat: [ self doStuff ]
```

How to change that so that we get it in Pharo11? 

Somehow the package is neither really external nor internal, that is, I have no idea how to commit a change.

**Comment by adri09070** [comment]
I found where Sindarin is imported!

It's imported from 
```Smalltalk
BaselineOfNewTools>>#sindarin:
```

So you can do the changes I suggested above and modify the URL in this method in NewTools

**Comment by MarcusDenker** [comment]
In the end this was in the NewTools package....

https://github.com/pharo-spec/NewTools/pull/394

**Comment by MarcusDenker** [comment]
I merged the PR
