### ISSUE TITLE
Cleanup: do not use #notNil, use #isNotNil instead

### ISSUE THREAD

**Issue by astares** [pharo-spec/ScriptableDebugger#95]
We have three cases in Sindarin where #notNil is sent instead of #isNotNil
Our plan is to deprecated #notNil in Pharo 13 so we would like to cleanup all senders first.

![Screenshot from 2024-05-16 20 21 43](https://github.com/pharo-spec/ScriptableDebugger/assets/5980033/291c63d9-7295-463a-b35c-d88b11cb4fde)

see https://github.com/pharo-project/pharo/issues/15118

**Comment by astares** [comment]
@StevenCostiou would you be able to check and if OK merge this one

**Comment by jecisc** [comment]
Done
